---
# This is a simpler, self-contained version of job_report.yml.
- name: Run jobs and generate simple report
  hosts: "{{ hosts_apply }}"
  gather_facts: no
  order: sorted

  collections:
    - ansible.builtin
    - community.general

  vars_prompt:
    - name: "hosts_apply"
      prompt: "Host or Group to apply this Playbook"
      private: no
    - name: "output_dir"
      prompt: "Output Directory Report"
      private: no

  vars:
    # Location for job reports
    outdir: "{{ output_dir }}"
  
  pre_tasks:
    
    - name: Create output folder
      run_once: yes
      delegate_to: localhost
      file:
        path: "{{ outdir }}"
        state: directory
    
  tasks:
    
    # Add your own tasks here! #
    
    - name: Run a command and save the results
      command:
        cmd: dnf check-update
      register: cmd1_results
  
  post_tasks:
  
    - name: Save some useful facts under Ansible controller
      delegate_to: localhost
      delegate_facts: True
      run_once: yes
      set_fact:
        date_str: "{{ date }}_{{ hms }}"
        date_str_pretty: "{{ date }} {{ hms_pretty }}" 
        success_list: "{{ ansible_play_hosts }}"
        failed_list: "{{ ansible_play_hosts_all | difference(ansible_play_hosts) }}"
      vars:
        date: "{{ '%Y-%m-%d' | strftime }}"
        hms_pretty: "{{ '%H:%M:%S' | strftime }}"
        hms: "{{ hms_pretty | replace(':','-') }}"
        
    # The template module is a better alternative for larger or more complex reports.
    - name: Save simple job report to {{ outdir }} on Ansible server
      delegate_to: localhost
      delegate_facts: True
      run_once: yes
      copy:
        content: |
          <html>
          <body>
          <h1 id="top">Job Report for {{ hostvars['localhost']['date_str_pretty'] }}</h1>
          <hr>
          <p><strong>Host Totals:</strong></p>
            <ul>
              <li>Successful: {{ hostvars['localhost']['success_list']|length }} </li>
              <li>Failed: {{ hostvars['localhost']['failed_list']|length }}</li>
              <li>Total: {{ ansible_play_hosts_all|length }}</li>
            </ul>
            {%- if hostvars['localhost']['failed_list']|length > 0 %}
            <p style="color:fuchsia;"><strong>Failed hosts:</strong> {{ hostvars['localhost']['failed_list']|join(',') }}</p>
            {%- endif %}
            {% for h in ansible_play_hosts_all | sort %}
            <hr>
            <h3>{{ h }}: {{ 'success' if h in ansible_play_hosts else 'failed' }}</h3>
            <p>Output: </p><pre>{{ hostvars[h]['cmd1_results']['stdout']|d('no output')|trim }}</pre>
            <p>Errors: </p><pre>{{ hostvars[h]['cmd1_results']['sterr']|d('no errors')|trim }}</pre>
            {% endfor %}
            <hr>
            <p><i>Generated by Ansible playbook <strong>{{ playbook_dir }}/job_report_simple.yaml.</strong></i></p>
          </body>
          </html>
        dest: "{{ outdir }}/job_report_simple_{{ hostvars['localhost']['date_str'] }}.html"