---

- name: Run jobs and generate report
  hosts: "{{ hosts_apply }}"
  gather_facts: no
  order: sorted

  collections:
    - ansible.builtin
    - community.general

  vars_prompt:
    - name: "hosts_apply"
      prompt: "Host or Group to apply this Playbook"
      private: no
    - name: "output_dir"
      prompt: "Output Directory Report"
      private: no

  vars:
    # Location for job reports
    outdir: "{{ output_dir }}"
    # CSS styling for navbar: menu width, failed/missing colors
    nav_width: 200px
    failed_style: 'color:orangered'
    missing_style: 'color:grey;text-decoration:line-through'
    # Email options
    send_email: false
    smtp_host: mail.yourcompany.com
    smtp_port: 25
    mail_from: "source@email.com"
    mail_to: "dest1@email.com,dest2@email.com"
    mail_subject: "Ansible job report"
    # Uncomment these if authentication is required
    #smtp_user:
    #smtp_pass: 

  pre_tasks:
    
    - name: Create output folder
      run_once: yes
      delegate_to: localhost
      file:
        path: "{{ outdir }}"
        state: directory
    
    # We set hosts as failed/missing until proven otherwise. See README.md
    - name: Set initial job status to catch missing/failed hosts
      set_fact:
        job_success: False
        missing: True
    
    - name: Gather server facts and weed out unavailable hosts
      setup:
    
    - name: Set remaining hosts as not missing
      set_fact:
        missing: False

  tasks:
    
    ############################
    # Add your own tasks here! #
    ############################
    
    - name: Run a command and save the results (ignore errors)
      command:
        cmd: echo "This is output from command 1."
      ignore_errors: yes
      register: cmd1_results

  post_tasks:

    - name: Mark surviving hosts as successful
      set_fact:
        job_success: True

    # Saving curated lists of hosts as localhost facts, to make the Jinja loops easier to read in the template. 
    # To use: hostvars['localhost']['success_list'] , etc
    - name: Save summary facts under Ansible controller
      delegate_to: localhost
      delegate_facts: True
      run_once: yes
      set_fact:
        date_str: "{{ date }}_{{ hms }}"
        date_str_pretty: "{{ date }} {{ hms_pretty }}"
        kernels_list: '{{ hostvars | json_query(kernel_query) | unique | sort }}'
        success_list: '{{ hostvars | dict2items | json_query(success_query) }}'
        failed_list: '{{ hostvars | dict2items | json_query(failed_query) }}'
        missing_list: '{{ hostvars | dict2items | json_query(missing_query) }}'
      vars:
        kernel_query: "*.ansible_kernel"
        success_query: "[?value.job_success==`true`].key"
        failed_query: "[?value.job_success==`false` && value.missing==`false`].key"
        missing_query: "[?value.missing==`true`].key"
        date: "{{ '%Y-%m-%d' | strftime }}"
        hms_pretty: "{{ '%H:%M:%S' | strftime }}"
        hms: "{{ hms_pretty | replace(':','-') }}"

    - name: Save job report to {{ outdir }}
      delegate_to: localhost
      delegate_facts: True
      run_once: yes
      template:
        src: job_report_master.j2
        dest: "{{ outdir  }}/job_report_{{ hostvars['localhost']['date_str'] }}.html"

    - name: Send email report from Ansible server
      delegate_to: localhost
      run_once: yes
      when: send_email
      mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_user | default(omit) }}"
        password: "{{ smtp_pass | default(omit) }}"
        from: "{{ mail_from }}"
        to: "{{ mail_to }}"
        subject: "{{ mail_subject }}"
        subtype: html
        body: |
          <p>See attached for a detailed job report.</p>
          <p><strong>Successful hosts</strong>:<br><br>{{ hostvars['localhost']['success_list'] | join(' ') }}</p>
          <p style="color:red;"><strong>Failed hosts</strong>: <br><br>{{ hostvars['localhost']['failed_list'] | join(' ') }}</p>
          <p style="color:fuchsia;"><strong>Missing hosts</strong>: {{ hostvars['localhost']['missing_list'] | join(' ') }}</p>
          <p><i>Generated by playbook {{ playbook_dir }}/job_report.yaml on {{ hostvars['localhost']['date_str_pretty'] }}</i></p>
        attach:
          - "{{ outdir }}/job_report_{{ hostvars['localhost']['date_str'] }}.html"
